### ISSUE TITLE
#M01. Setup Blueprint App structure and add instructions in Readme

### ISSUE THREAD

**Issue by stefdworschak** [Code-Institute-Community/business-analysis-project#56]

**Comment by auxfuse** [comment]
@alissatroiano Just letting you know that we have a PR in from @stefdworschak targetting this issue. I recognise that you have assigned yourself this task, but just to make sure that you aren't doing a huge amount of work on it. 🤜

**Comment by auxfuse** [comment]
Closing to suit PR #57

**Comment by alissatroiano** [comment]
I did notice that @stefdworschak was setting this up, so I stopped working on this. I wasn’t sure if he was just doing directory structure or Blueprints too, but I get it now. Thanks for letting me know @auxfuse
